name: cue_cli
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
   path: ^1.8.0
   args: ^2.7.0
   process_run: ^1.2.4
   build_runner: ^2.4.15
   logger: ^2.5.0
   pubspec_yaml: ^3.1.0

dev_dependencies:
  lints: ^5.0.0

executables:
  cue: cue_cli